# Generated by Django 5.1.7 on 2025-03-30 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(blank=True, max_length=12, unique=True, verbose_name='邀请码')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='级别')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to='users.userprofile', verbose_name='邀请人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=12, verbose_name='使用的邀请码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='邀请时间')),
                ('status', models.CharField(choices=[('pending', '待接受'), ('accepted', '已接受'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitation', to='users.userprofile', verbose_name='被邀请人')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='users.userprofile', verbose_name='邀请人')),
            ],
            options={
                'verbose_name': '邀请记录',
                'verbose_name_plural': '邀请记录',
                'ordering': ['-created_at'],
                'unique_together': {('inviter', 'invitee')},
            },
        ),
    ]
