# Generated by Django 5.1.7 on 2025-03-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ban_count',
            field=models.PositiveIntegerField(default=0, verbose_name='封号次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='封号原因'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='封号截止时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='是否封号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_ban_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近封号时间'),
        ),
    ]
