# Generated by Django 5.1.7 on 2025-04-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram聊天ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_connected',
            field=models.BooleanField(default=False, verbose_name='是否绑定Telegram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram绑定令牌'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='令牌创建时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram用户名'),
        ),
    ]
