# Generated by Django 5.1.7 on 2025-03-30 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='商品分类',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名称', models.CharField(max_length=100, verbose_name='分类名称')),
                ('级别', models.PositiveIntegerField(default=1, verbose_name='分类级别')),
                ('是否启用', models.BooleanField(default=True, verbose_name='是否启用')),
                ('排序', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('创建时间', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('父类', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='子类', to='商品.商品分类', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['排序'],
            },
        ),
        migrations.CreateModel(
            name='商品',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名称', models.CharField(max_length=200, verbose_name='商品名称')),
                ('价格', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('原价', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('库存', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('销量', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('主图', models.ImageField(blank=True, null=True, upload_to='商品/图片/', verbose_name='主图')),
                ('描述', models.TextField(blank=True, verbose_name='商品描述')),
                ('状态', models.CharField(choices=[('草稿', '草稿'), ('已发布', '已发布'), ('已售罄', '已售罄'), ('已下架', '已下架')], default='草稿', max_length=20, verbose_name='状态')),
                ('是否推荐', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('是否热门', models.BooleanField(default=False, verbose_name='是否热门')),
                ('是否新品', models.BooleanField(default=True, verbose_name='是否新品')),
                ('创建时间', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('更新时间', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('分类', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='商品', to='商品.商品分类', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-创建时间'],
            },
        ),
    ]
