# Generated by Django 5.1.7 on 2025-03-30 02:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('share_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='分享码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists_new', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '心愿单',
                'verbose_name_plural': '心愿单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='货币')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wishlist_items/', verbose_name='图片')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级')),
                ('purchased', models.BooleanField(default=False, verbose_name='已被购买')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='购买时间')),
                ('payment_status', models.CharField(blank=True, max_length=20, verbose_name='支付状态')),
                ('payment_completed', models.BooleanField(default=False, verbose_name='支付已完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_item_new', to='payment.payment', verbose_name='当前支付')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_items_new', to=settings.AUTH_USER_MODEL, verbose_name='购买者')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist_new.wishlist', verbose_name='心愿单')),
            ],
            options={
                'verbose_name': '心愿单物品',
                'verbose_name_plural': '心愿单物品',
                'ordering': ['-created_at', 'priority'],
            },
        ),
    ]
