# Generated by Django 5.1.7 on 2025-04-08 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_goods_desc_goods_source_url_and_more'),
        ('wishlist_new', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-added_at', 'priority'], 'verbose_name': '心愿单商品', 'verbose_name_plural': '心愿单商品'},
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist_new.wishlist', verbose_name='心愿单'),
        ),
    ]
