# Generated by Django 5.1.7 on 2025-04-30 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods_visible_in'),
        ('payment', '0009_wishlistvisitlog'),
        ('wishlist_new', '0003_wishlistview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlist'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-added_at', 'priority'], 'verbose_name': 'Wishlist Item', 'verbose_name_plural': 'Wishlist Item'},
        ),
        migrations.AlterModelOptions(
            name='wishlistview',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'Wishlist View Record', 'verbose_name_plural': 'Wishlist View Record'},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is Public'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='share_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Share Code'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added At'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='current_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_item_new', to='payment.payment', verbose_name='Current Payment'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist_items/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='payment_completed',
            field=models.BooleanField(default=False, verbose_name='Payment Completed'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='purchased',
            field=models.BooleanField(default=False, verbose_name='Purchased'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Purchase Time'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_items_new', to=settings.AUTH_USER_MODEL, verbose_name='Purchaser'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist_new.wishlist', verbose_name='Wishlist'),
        ),
        migrations.AlterField(
            model_name='wishlistview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='wishlistview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='wishlistview',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='View Time'),
        ),
        migrations.AlterField(
            model_name='wishlistview',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='wishlist_new.wishlist', verbose_name='Wishlist'),
        ),
    ]
