# Generated by Django 5.1.7 on 2025-05-03 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods_visible_in'),
        ('payment', '0010_remove_payment_reference_id_and_more'),
        ('wishlist_new', '0005_alter_wishlist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at'], 'verbose_name': '心愿单', 'verbose_name_plural': '心愿单'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-added_at', 'priority'], 'verbose_name': '心愿单商品', 'verbose_name_plural': '心愿单商品'},
        ),
        migrations.AlterModelOptions(
            name='wishlistview',
            options={'ordering': ['-viewed_at'], 'verbose_name': '心愿单浏览记录', 'verbose_name_plural': '心愿单浏览记录'},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='share_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='分享码'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists_new', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='current_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_item_new', to='payment.payment', verbose_name='当前支付'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist_items/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='payment_completed',
            field=models.BooleanField(default=False, verbose_name='支付已完成'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='purchased',
            field=models.BooleanField(default=False, verbose_name='已被购买'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_items_new', to=settings.AUTH_USER_MODEL, verbose_name='购买者'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='url',
            field=models.URLField(blank=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist_new.wishlist', verbose_name='心愿单'),
        ),
        migrations.AlterField(
            model_name='wishlistview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='wishlistview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='wishlistview',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='浏览时间'),
        ),
        migrations.AlterField(
            model_name='wishlistview',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='wishlist_new.wishlist', verbose_name='心愿单'),
        ),
    ]
