# Generated by Django 5.1.7 on 2025-03-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='支付配置参数（API密钥等）'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='test_mode',
            field=models.BooleanField(default=True, help_text='是否启用测试模式'),
        ),
    ]
