# Generated by Django 5.1.7 on 2025-03-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20250330_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='wishlist_item',
            field=models.ForeignKey(blank=True, help_text='关联的心愿单物品', null=True, on_delete=models.deletion.CASCADE, related_name='payments', to='wishlist_new.wishlistitem'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='交易ID', max_length=255, null=True),
        ),
    ]
