# Generated by Django 5.1.7 on 2025-04-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20250330_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('usdt', 'USDT'), ('paypal', 'PayPal'), ('credit_card', '信用卡'), ('coinbase_commerce', 'Coinbase商务')], help_text='支付类型', max_length=20),
        ),
        migrations.CreateModel(
            name='CoinbaseCommercePaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(blank=True, help_text='Coinbase Charge ID', max_length=255, null=True)),
                ('charge_code', models.CharField(blank=True, help_text='Coinbase Charge Code', max_length=255, null=True)),
                ('hosted_url', models.URLField(blank=True, help_text='支付托管URL', null=True)),
                ('status', models.CharField(blank=True, help_text='Coinbase支付状态', max_length=50, null=True)),
                ('crypto_used', models.CharField(blank=True, help_text='使用的加密货币', max_length=50, null=True)),
                ('payment', models.OneToOneField(help_text='关联的支付记录', on_delete=django.db.models.deletion.CASCADE, related_name='coinbase_commerce_details', to='payment.payment')),
            ],
            options={
                'verbose_name': 'Coinbase商务支付详情',
                'verbose_name_plural': 'Coinbase商务支付详情',
            },
        ),
    ]
