# Generated by Django 5.1.7 on 2025-04-26 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymentmethod_payment_type_and_more'),
        ('wishlist_new', '0003_wishlistview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinbasecommercepaymentdetail',
            options={'verbose_name': 'Coinbase Commerce Payment Detail', 'verbose_name_plural': 'Coinbase Commerce Payment Details'},
        ),
        migrations.AlterModelOptions(
            name='creditcardpaymentdetail',
            options={'verbose_name': 'Credit Card Payment Detail', 'verbose_name_plural': 'Credit Card Payment Details'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Record', 'verbose_name_plural': 'Payment Records'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='paymentwebhooklog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Webhook Log', 'verbose_name_plural': 'Webhook Logs'},
        ),
        migrations.AlterModelOptions(
            name='paypalpaymentdetail',
            options={'verbose_name': 'PayPal Payment Detail', 'verbose_name_plural': 'PayPal Payment Details'},
        ),
        migrations.AlterModelOptions(
            name='usdtpaymentdetail',
            options={'verbose_name': 'USDT Payment Detail', 'verbose_name_plural': 'USDT Payment Details'},
        ),
        migrations.AlterField(
            model_name='coinbasecommercepaymentdetail',
            name='crypto_used',
            field=models.CharField(blank=True, help_text='Cryptocurrency used', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coinbasecommercepaymentdetail',
            name='hosted_url',
            field=models.URLField(blank=True, help_text='Payment hosted URL', null=True),
        ),
        migrations.AlterField(
            model_name='coinbasecommercepaymentdetail',
            name='payment',
            field=models.OneToOneField(help_text='Related payment record', on_delete=django.db.models.deletion.CASCADE, related_name='coinbase_commerce_details', to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='coinbasecommercepaymentdetail',
            name='status',
            field=models.CharField(blank=True, help_text='Coinbase payment status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardpaymentdetail',
            name='card_type',
            field=models.CharField(blank=True, help_text='Card type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardpaymentdetail',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditcardpaymentdetail',
            name='last_four',
            field=models.CharField(blank=True, help_text='Last four digits', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardpaymentdetail',
            name='payment',
            field=models.OneToOneField(help_text='Related payment record', on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_details', to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='creditcardpaymentdetail',
            name='processor',
            field=models.CharField(default='stripe', help_text='Processor', max_length=50),
        ),
        migrations.AlterField(
            model_name='creditcardpaymentdetail',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Completed at', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Anonymous payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(blank=True, help_text='Payer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_email',
            field=models.EmailField(blank=True, help_text='Payer email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, help_text='Payer name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_data',
            field=models.JSONField(default=dict, help_text='Payment related data'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(help_text='Payment method', on_delete=django.db.models.deletion.PROTECT, to='payment.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_message',
            field=models.CharField(blank=True, help_text='Status message', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='wishlist_item',
            field=models.ForeignKey(blank=True, help_text='Related wishlist item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wishlist_new.wishlistitem'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(help_text='Payment method code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Payment configuration parameters (API keys, etc.)'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, help_text='Payment method description', null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.ImageField(blank=True, help_text='Payment method icon', null=True, upload_to='payment_icons/'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is active'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(help_text='Payment method name', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('usdt', 'USDT'), ('paypal', 'PayPal'), ('credit_card', 'Credit Card'), ('coinbase_commerce', 'Coinbase Commerce')], help_text='Payment type', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='test_mode',
            field=models.BooleanField(default=True, help_text='Enable test mode'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated at'),
        ),
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created at'),
        ),
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='event_type',
            field=models.CharField(help_text='Event type', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='payload',
            field=models.JSONField(default=dict, help_text='Original request data'),
        ),
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='response',
            field=models.JSONField(default=dict, help_text='Response data'),
        ),
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='status',
            field=models.CharField(default='pending', help_text='Processing status', max_length=20),
        ),
        migrations.AlterField(
            model_name='paypalpaymentdetail',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paypalpaymentdetail',
            name='payment',
            field=models.OneToOneField(help_text='Related payment record', on_delete=django.db.models.deletion.CASCADE, related_name='paypal_details', to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='paypalpaymentdetail',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Payment link', null=True),
        ),
        migrations.AlterField(
            model_name='paypalpaymentdetail',
            name='paypal_order_id',
            field=models.CharField(blank=True, help_text='PayPal order ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paypalpaymentdetail',
            name='paypal_payer_id',
            field=models.CharField(blank=True, help_text='PayPal payer ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usdtpaymentdetail',
            name='confirmation_count',
            field=models.PositiveIntegerField(default=0, help_text='Confirmation count'),
        ),
        migrations.AlterField(
            model_name='usdtpaymentdetail',
            name='network',
            field=models.CharField(default='trc20', help_text='USDT network', max_length=20),
        ),
        migrations.AlterField(
            model_name='usdtpaymentdetail',
            name='payment',
            field=models.OneToOneField(help_text='Related payment record', on_delete=django.db.models.deletion.CASCADE, related_name='usdt_details', to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='usdtpaymentdetail',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Payment QR code', null=True, upload_to='payment_qrcodes/'),
        ),
        migrations.AlterField(
            model_name='usdtpaymentdetail',
            name='sender_address',
            field=models.CharField(blank=True, help_text='Sender address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usdtpaymentdetail',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='Transaction hash', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usdtpaymentdetail',
            name='wallet_address',
            field=models.CharField(help_text='Wallet address', max_length=255),
        ),
    ]
