# Generated by Django 5.1.7 on 2025-04-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_payment_reference_id'),
        ('wishlist_new', '0003_wishlistview'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('region', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('device', models.CharField(blank=True, max_length=64, null=True)),
                ('browser', models.CharField(blank=True, max_length=64, null=True)),
                ('os', models.CharField(blank=True, max_length=64, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
                ('wishlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='wishlist_new.wishlistitem')),
            ],
            options={
                'verbose_name': 'Wishlist Visit Log',
                'verbose_name_plural': 'Wishlist Visit Logs',
                'ordering': ['-visited_at'],
            },
        ),
    ]
