# Generated by Django 5.1.7 on 2025-05-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_wishlistvisitlog'),
        ('wishlist_new', '0005_alter_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='wishlist_item',
            field=models.ForeignKey(blank=True, help_text='关联的心愿单物品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wishlist_new.wishlistitem'),
        ),
        migrations.DeleteModel(
            name='WishlistVisitLog',
        ),
    ]
