# Generated by Django 5.1.7 on 2025-05-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_remove_payment_reference_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinbaseCommercePaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(blank=True, help_text='Coinbase Charge ID', max_length=255, null=True)),
                ('charge_code', models.CharField(blank=True, help_text='Coinbase Charge Code', max_length=255, null=True)),
                ('hosted_url', models.URLField(blank=True, help_text='支付托管URL', null=True)),
                ('status', models.CharField(default='NEW', help_text='支付状态', max_length=50)),
                ('crypto_used', models.CharField(blank=True, help_text='使用的加密货币', max_length=20, null=True)),
                ('payment', models.OneToOneField(help_text='关联的支付记录', on_delete=django.db.models.deletion.CASCADE, related_name='coinbase_details', to='payment.payment')),
            ],
            options={
                'verbose_name': 'Coinbase商务支付详情',
                'verbose_name_plural': 'Coinbase商务支付详情',
            },
        ),
    ]
