# Generated by Django 5.1.7 on 2025-03-30 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20250330_1049'),
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='货币'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='current_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_item', to='payment.payment', verbose_name='当前支付'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist_items/', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='payment_completed',
            field=models.BooleanField(default=False, verbose_name='支付已完成'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='purchased',
            field=models.BooleanField(default=False, verbose_name='已被购买'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='购买时间'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_items', to=settings.AUTH_USER_MODEL, verbose_name='购买者'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='url',
            field=models.URLField(blank=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlist', verbose_name='心愿单'),
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='quantity',
        ),
    ]
