# Generated by Django 5.1.7 on 2025-04-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_goods_desc_goods_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='visible_in',
            field=models.JSONField(blank=True, default=list, verbose_name='可见站点'),
        ),
    ]
