# Generated by Django 5.1.7 on 2025-03-30 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=100, verbose_name='Bot Token')),
                ('bot_username', models.CharField(blank=True, max_length=100, verbose_name='Bot 用户名')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('webhook_url', models.URLField(blank=True, verbose_name='Webhook URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Telegram机器人设置',
                'verbose_name_plural': 'Telegram机器人设置',
            },
        ),
        migrations.CreateModel(
            name='UserTelegramBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram用户名')),
                ('telegram_first_name', models.CharField(blank=True, max_length=100, verbose_name='Telegram名')),
                ('telegram_last_name', models.CharField(blank=True, max_length=100, verbose_name='Telegram姓')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用通知')),
                ('verification_code', models.CharField(blank=True, max_length=20, verbose_name='验证码')),
                ('verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_binding', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户Telegram绑定',
                'verbose_name_plural': '用户Telegram绑定',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_wishlist_view', models.BooleanField(default=True, verbose_name='心愿单被查看通知')),
                ('notify_wishlist_purchase', models.BooleanField(default=True, verbose_name='心愿单物品购买通知')),
                ('notify_system_message', models.BooleanField(default=True, verbose_name='系统消息通知')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='免打扰开始时间')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='免打扰结束时间')),
                ('user_binding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='telegram_bot.usertelegrambinding', verbose_name='绑定关系')),
            ],
            options={
                'verbose_name': 'Telegram通知设置',
                'verbose_name_plural': 'Telegram通知设置',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('wishlist_view', '心愿单被查看'), ('wishlist_purchase', '心愿单物品购买'), ('system', '系统消息')], max_length=20, verbose_name='通知类型')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='关联对象类型')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败')], default='pending', max_length=10, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('user_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telegram_bot.usertelegrambinding', verbose_name='绑定关系')),
            ],
            options={
                'verbose_name': 'Telegram通知记录',
                'verbose_name_plural': 'Telegram通知记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
