# Generated by Django 5.1.7 on 2025-04-13 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=100, verbose_name='Bot Token')),
                ('webhook_url', models.URLField(verbose_name='Webhook URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Telegram机器人配置',
                'verbose_name_plural': 'Telegram机器人配置',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, verbose_name='聊天ID')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('is_sent', models.BooleanField(default=False, verbose_name='是否已发送')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': 'Telegram消息记录',
                'verbose_name_plural': 'Telegram消息记录',
                'ordering': ['-sent_at'],
            },
        ),
    ]
