# Generated by Django 5.1.7 on 2025-04-13 21:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('code', models.SlugField(help_text='唯一的站点标识符，用于API请求和URL', unique=True, validators=[django.core.validators.RegexValidator(message='站点代码只能包含小写字母、数字、下划线和连字符', regex='^[a-z0-9_-]+$')], verbose_name='站点代码')),
                ('domain', models.CharField(blank=True, help_text='站点的主域名，例如：example.com', max_length=100, verbose_name='域名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sites/logos/', verbose_name='站点Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='sites/favicons/', verbose_name='站点图标')),
                ('primary_color', models.CharField(blank=True, default='#3b82f6', max_length=20, verbose_name='主色调')),
                ('secondary_color', models.CharField(blank=True, default='#10b981', max_length=20, verbose_name='次色调')),
                ('api_url', models.URLField(blank=True, help_text='站点API的基础URL，如果为空则使用默认URL', verbose_name='API URL')),
                ('api_key', models.CharField(blank=True, max_length=100, verbose_name='API密钥')),
                ('frontend_url', models.URLField(blank=True, help_text='前端应用的URL，如果为空则使用域名', verbose_name='前端URL')),
                ('frontend_port', models.PositiveIntegerField(default=3000, help_text='前端应用运行的端口', verbose_name='前端端口')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点管理',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_address', models.TextField(blank=True, verbose_name='联系地址')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook链接')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter链接')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram链接')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube链接')),
                ('meta_title', models.CharField(blank=True, max_length=100, verbose_name='Meta标题')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta描述')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='Meta关键词')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='sites.site')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
        migrations.CreateModel(
            name='SiteSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('image', models.ImageField(upload_to='sites/slides/', verbose_name='图片')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='按钮文字')),
                ('button_link', models.CharField(blank=True, max_length=200, verbose_name='按钮链接')),
                ('background_color', models.CharField(blank=True, default='bg-gradient-to-r from-primary-700 to-primary-900', max_length=20, verbose_name='背景颜色')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='sites.site')),
            ],
            options={
                'verbose_name': '首页幻灯片',
                'verbose_name_plural': '首页幻灯片',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg_color', models.CharField(blank=True, default='#ffffff', max_length=20, verbose_name='头部背景色')),
                ('footer_bg_color', models.CharField(blank=True, default='#1f2937', max_length=20, verbose_name='底部背景色')),
                ('button_color', models.CharField(blank=True, default='#3b82f6', max_length=20, verbose_name='按钮颜色')),
                ('link_color', models.CharField(blank=True, default='#3b82f6', max_length=20, verbose_name='链接颜色')),
                ('heading_font', models.CharField(blank=True, default='sans-serif', max_length=50, verbose_name='标题字体')),
                ('body_font', models.CharField(blank=True, default='sans-serif', max_length=50, verbose_name='正文字体')),
                ('layout_type', models.CharField(choices=[('default', '默认'), ('compact', '紧凑'), ('wide', '宽屏')], default='default', max_length=20, verbose_name='布局类型')),
                ('custom_css', models.TextField(blank=True, verbose_name='自定义CSS')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='sites.site')),
            ],
            options={
                'verbose_name': '站点主题',
                'verbose_name_plural': '站点主题',
            },
        ),
    ]
