# Generated by Django 5.1.7 on 2025-04-08 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0003_goods_visible_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='区块标题')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('block_type', models.CharField(choices=[('product_list', '商品列表'), ('image_text', '图文组合'), ('brand_list', '品牌列表'), ('category_icons', '分类图标'), ('coupon_list', '优惠券列表')], max_length=20, verbose_name='区块类型')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='区块内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/', verbose_name='区块图片')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='链接地址')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('visible_in', models.JSONField(blank=True, default=list, verbose_name='可见站点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页区块',
                'verbose_name_plural': '首页区块',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='轮播图片')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='链接地址')),
                ('position', models.CharField(choices=[('home_top', '首页顶部'), ('home_middle', '首页中部'), ('category', '分类页面'), ('product', '商品详情页')], default='home_top', max_length=20, verbose_name='显示位置')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('visible_in', models.JSONField(blank=True, default=list, verbose_name='可见站点')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goods', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['sort_order'],
            },
        ),
    ]
