# Generated by Django 5.1.7 on 2025-05-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='设置键名')),
                ('value', models.JSONField(default=dict, verbose_name='设置值')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('about', '关于我们'), ('policy', '政策条款'), ('shopping', '购物指南'), ('help', '帮助中心')], max_length=50, verbose_name='分类')),
                ('slug', models.SlugField(max_length=100, verbose_name='页面标识')),
                ('title', models.CharField(max_length=200, verbose_name='页面标题')),
                ('content', models.TextField(verbose_name='页面内容')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO标题')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO描述')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('visible_in', models.JSONField(blank=True, default=list, verbose_name='可见站点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '页面内容',
                'verbose_name_plural': '页面内容',
                'ordering': ['category', 'sort_order', 'slug'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
