# Generated by Django 5.1.7 on 2025-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_sitesettings_pagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['category', 'sort_order'], 'verbose_name': '页面内容', 'verbose_name_plural': '页面内容'},
        ),
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='html_content',
            field=models.TextField(blank=True, verbose_name='HTML内容'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='副标题'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='category',
            field=models.CharField(choices=[('about', '关于我们'), ('shopping', '购物指南'), ('policy', '政策条款'), ('help', '帮助中心'), ('custom', '自定义页面')], max_length=50, verbose_name='内容分类'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta描述'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Meta标题'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='页面标识'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True, verbose_name='设置描述'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='value',
            field=models.JSONField(blank=True, default=dict, verbose_name='设置值'),
        ),
    ]
