"""
Django settings for mall project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uzw3=3!+i2$er9+2n12eo@_0-=n39a7wf1n91@6+!1li0!37ax'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '81af-2001-e68-82c4-1600-9043-411-b72d-3f62.ngrok-free.app',
    '7a77-60-48-150-169.ngrok-free.app',  # 新增的ngrok域名
    '*.ngrok-free.app',  # 允许所有ngrok域名，因为每次重启ngrok会生成新域名
    '*',  # 允许所有域名，生产环境应该替换为你的实际域名
]

# CSRF信任的来源域名
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:4400',
    'http://localhost:4400',
    'https://7a77-60-48-150-169.ngrok-free.app',
    'http://7a77-60-48-150-169.ngrok-free.app',
    'https://*.ngrok-free.app',  # 所有ngrok域名
]


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'goods',
    'wishlist',
    'wishlist_new',
    'users',
    'telegram_bot',
    'channels',
    'payment',
    'order',
    # 'cart',  # 暂时禁用购物车功能，使用心愿单替代
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Site URL (用于生成完整的URL，如Telegram通知中的链接)
SITE_URL = 'http://127.0.0.1:8080'

# Telegram Bot配置
TELEGRAM_WEBHOOK_BASE_URL = 'https://example.com'  # 使用ngrok等工具暴露的URL

# Celery配置
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Simpleui配置 - 自定义菜单
SIMPLEUI_CONFIG = {
    'system_keep': False,  # 不保留系统菜单
    'menus': [
        {
            'name': '商品管理',
            'icon': 'fas fa-shopping-bag',
            'models': [
                {
                    'name': '商品',
                    'url': 'goods/goods/',
                    'icon': 'fa fa-shopping-cart'
                }
            ]
        },
        {
            'name': '心愿单',
            'icon': 'fas fa-heart',
            'models': [
                {
                    'name': '心愿单',
                    'url': 'wishlist_new/wishlist/',
                    'icon': 'fa fa-list'
                },
                {
                    'name': '心愿单物品',
                    'url': 'wishlist_new/wishlistitem/',
                    'icon': 'fa fa-gift'
                }
            ]
        },
        {
            'name': 'Telegram机器人',
            'icon': 'fab fa-telegram',
            'models': [
                {
                    'name': 'Telegram配置',
                    'url': 'telegram_bot/telegrambotsettings/',
                    'icon': 'fa fa-cog'
                },
                {
                    'name': '消息记录',
                    'url': 'telegram_bot/telegramnotification/',
                    'icon': 'fa fa-comment'
                }
            ]
        },
        {
            'name': '订单管理',
            'icon': 'fas fa-file-invoice',
            'models': [
                {
                    'name': '订单',
                    'url': 'order/order/',
                    'icon': 'fa fa-clipboard-list'
                },
                {
                    'name': '退款详情',
                    'url': 'order/refunddetail/',
                    'icon': 'fa fa-money-bill-wave'
                },
                {
                    'name': '订单日志',
                    'url': 'order/orderlog/',
                    'icon': 'fa fa-history'
                }
            ]
        },
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '用户',
                    'url': 'auth/user/',
                    'icon': 'fa fa-user'
                },
                {
                    'name': '收货地址',
                    'url': 'users/shippingaddress/',
                    'icon': 'fa fa-map-marker-alt'
                },
                {
                    'name': '邀请记录',
                    'url': 'users/invitationrecord/',
                    'icon': 'fa fa-user-plus'
                }
            ]
        },
        {
            'name': '支付',
            'icon': 'fas fa-credit-card',
            'models': [
                {
                    'name': '支付方式',
                    'url': 'payment/paymentmethod/',
                    'icon': 'fa fa-wallet'
                },
                {
                    'name': '支付记录',
                    'url': 'payment/payment/',
                    'icon': 'fa fa-receipt'
                },
                {
                    'name': 'Webhook日志',
                    'url': 'payment/paymentwebhooklog/',
                    'icon': 'fa fa-clipboard-check'
                }
            ]
        }
    ]
}

# Channels配置
ASGI_APPLICATION = 'mall.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
        # 生产环境使用Redis作为后端
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [('127.0.0.1', 6379)],
        # },
    },
}

# 用户登录相关设置
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
