# Generated by Django 5.1.7 on 2025-03-30 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0003_auto_20250330_1049'),
        ('users', '0003_shippingaddress'),
        ('wishlist_new', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总额')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='货币')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('paid', '已支付'), ('processing', '处理中'), ('shipped', '已发货'), ('delivered', '已送达'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunding', '退款中'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='收件人姓名')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='收件人电话')),
                ('shipping_address_text', models.TextField(verbose_name='收货地址文本')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='物流单号')),
                ('shipping_carrier', models.CharField(blank=True, max_length=50, verbose_name='物流公司')),
                ('shipping_method', models.CharField(blank=True, max_length=50, verbose_name='配送方式')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('is_refunding', models.BooleanField(default=False, verbose_name='是否申请退款')),
                ('refund_status', models.CharField(blank=True, choices=[('pending', '待处理'), ('processing', '处理中'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成')], max_length=20, verbose_name='退款状态')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退款金额')),
                ('refund_reason', models.TextField(blank=True, verbose_name='退款原因')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('customer_notes', models.TextField(blank=True, verbose_name='客户备注')),
                ('admin_notes', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payment.payment', verbose_name='支付记录')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shippingaddress', verbose_name='收货地址')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('wishlist_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='wishlist_new.wishlistitem', verbose_name='心愿单物品')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('status_from', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('status_to', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='数据')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统操作')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='order.order', verbose_name='订单')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '订单日志',
                'verbose_name_plural': '订单日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退款金额')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='货币')),
                ('refund_method', models.CharField(max_length=50, verbose_name='退款方式')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('reason', models.CharField(max_length=100, verbose_name='退款原因')),
                ('description', models.TextField(blank=True, verbose_name='详细说明')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='交易ID')),
                ('refund_data', models.JSONField(blank=True, default=dict, verbose_name='退款数据')),
                ('admin_notes', models.TextField(blank=True, verbose_name='管理员备注')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='refund_receipts/', verbose_name='退款凭证')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_details', to='order.order', verbose_name='订单')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_details', to='payment.payment', verbose_name='原支付记录')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '退款详情',
                'verbose_name_plural': '退款详情',
                'ordering': ['-requested_at'],
            },
        ),
    ]
